baseURL = "https://koodikool.ee/"
languageCode = "et"
title = "Koodikool"
theme="hugo-theme-cactus-plus"
[Params]
bio="Koodikool algas kui vabas vormis programmeerimise 천petus. Lisandunud on vabas vormis Eesti haridusmaastiku uurimine ja v천imaluse korral parendamine l채bi kaasaegsete IT v천imaluste."